-- Create and use the database
CREATE DATABASE IF NOT EXISTS LEFTJOINING;
USE LEFTJOINING;

-- Create STUDENT1 table
CREATE TABLE IF NOT EXISTS STUDENT1 (
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(50)
);

-- Insert students
INSERT INTO STUDENT1
VALUES 
(101,"CHANDERMANI"),
(102,"ANKIT"),
(103,"AMIT"),
(104,"MAHESH"),
(105,"SARTHAK");

-- Create GIRLFRIEND table
CREATE TABLE IF NOT EXISTS GIRLFRIEND (
    STUDENT_ID INT,
    GIRLFRIEND_NAME VARCHAR(50)
);

-- Insert girlfriend data
INSERT INTO GIRLFRIEND
VALUES 
(101,"SCARLETT JOHANSSON AND HAYLEY ATWELL"),
(103,"ELIZABETH OLSEN"),
(104,"EMILIA CLARKE");

-- Perform LEFT JOIN
SELECT * 	
FROM STUDENT1 AS S1
LEFT JOIN GIRLFRIEND AS G 
ON S1.STUDENT_ID = G.STUDENT_ID;


-- PERFORM FULL JOIN
SELECT * 	
FROM STUDENT1 AS S1
LEFT JOIN GIRLFRIEND AS G 
ON S1.STUDENT_ID = G.STUDENT_ID
UNION
SELECT * 	
FROM STUDENT1 AS S1
LEFT JOIN GIRLFRIEND AS G 
ON S1.STUDENT_ID = G.STUDENT_ID;
