CREATE DATABASE IF NOT EXISTS PRACTICE;

USE PRACTICE;

CREATE TABLE IF NOT EXISTS STUDENTS_INFO (
	NAME VARCHAR(50),
    MARKS INT
);

-- Insert sample data
INSERT INTO STUDENTS_INFO (NAME, MARKS)
VALUES 
('CHANDERMANI', 95),
('ANKIT', 88),
('AMIT', 75),
('RIYA', 65);

-- Select with grade logic
SELECT 
    FULL_NAME,
    MARKS,
    CASE
        WHEN MARKS >= 90 THEN 'A+'
        WHEN MARKS >= 80 THEN 'A'
        WHEN MARKS >= 70 THEN 'B+'
        WHEN MARKS >= 60 THEN 'B'
        ELSE 'C'
    END AS GRADE
FROM STUDENTS_INFO;

ALTER TABLE STUDENTS_INFO
CHANGE NAME FULL_NAME VARCHAR(50);

SET SQL_SAFE_UPDATES = 0;

DELETE FROM STUDENTS_INFO
WHERE MARKS <= 70;
