CREATE DATABASE IF NOT EXISTS COLLEGE;

USE COLLEGE;

CREATE TABLE IF NOT EXISTS STUDENTS(
	ROLLNO INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(50),
    CITY VARCHAR(50),
    GRADE VARCHAR(2) DEFAULT "A+",
    COURSE VARCHAR(50) DEFAULT "B.TECH"
);

INSERT INTO STUDENTS (ROLLNO , STUDENT_NAME, CITY) 
VALUES (1,"CHANDERMANI MISHRA","SAMPLA"),
(2,"ANKIT KANDWAL","BAHADURGARH"),
(3,"AMIT KUMAR","DWARKA"),
(4,"MAHESH JANGRA","JHAJJAR"),
(5,"KESHAV SHARMA","JHAJJAR");

SELECT * FROM STUDENTS;
SELECT DISTINCT CITY FROM STUDENTS;