CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENTDETAILS(
	STUDENTNAME VARCHAR(30),
    FATHERNAME VARCHAR(30),
    AGE INT NOT NULL
);

INSERT INTO STUDENTDETAILS VALUES ("CHANDERMANI","DHANANJAY",20);
INSERT INTO STUDENTDETAILS VALUES ("ANKIT","CHANDERMANI",24);
INSERT INTO STUDENTDETAILS VALUES ("MAHESH","KESHAV",20);
INSERT INTO STUDENTDETAILS VALUES ("KESHAV","AMIT",20);
INSERT INTO STUDENTDETAILS VALUES ("AMIT","SARTHAK",20);

SELECT * FROM STUDENTDETAILS;