USE student;

DROP TABLE IF EXISTS studentdetails;

CREATE TABLE STUDENTDETAILS(
	ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO STUDENTDETAILS VALUES (02,"CHANDERMANI"),(04,"ANKIT KANDWAL"),(06,"AMIT KUMAR"),(24,"MAHESH") ,(19,"KESHAV");

SELECT * FROM STUDENTDETAILS;