USE STUDENT;

CREATE TABLE IF NOT EXISTS STUDENT_MARKS (
    NAME VARCHAR(50),
    MM INT DEFAULT 0,
    TOC INT DEFAULT 0,
    DCN INT DEFAULT 0,
    DBMS INT DEFAULT 0,
    WD INT DEFAULT 0,
    PRIMARY KEY (NAME)
);

-- Example insert (insert marks for a student already in STUDENTDETAILS)
INSERT INTO STUDENT_MARKS (NAME, MM, TOC, DCN, DBMS, WD)
VALUES ("CHANDERMANI", 80, 75, 78, 85, 90);

INSERT INTO STUDENT_MARKS (NAME) 
VALUES ("AMIT");

SELECT * FROM STUDENT_MARKS;
